# Generated by Django 2.1.7 on 2019-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20190529_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='ltp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equity',
            name='watch_price',
            field=models.FloatField(default=0.0),
        ),
    ]
