# Generated by Django 2.1.7 on 2019-06-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20190602_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='derivative',
            unique_together={('expiry_date', 'call', 'strike_price')},
        ),
    ]
