# Generated by Django 2.1.7 on 2019-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_auto_20190603_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='y_h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equity',
            name='y_l',
            field=models.FloatField(default=0.0),
        ),
    ]
